### ISSUE TITLE
Complete shiny code to derive the start and finish time for the event

### ISSUE THREAD

**Issue by jacgrout** [jacgrout/WebinarStats#7]
Currently the date of the event is derived from the data in the file using functions to get the modal date. Something similar for the start and finish times works in the non-shiny version in the tidythedata.R script. Incorporate this same functionality into the shiny app, but may possibly need to use median rather than mode. This needs some experimenting and testing. The app must have the facility to edit the start and finish times once derived. Currently they default to 9am to 5pm.

Functions to get the median hour and median minutes have now been added to functions_script.R

**Comment by ChrisBeeley** [comment]
See here https://github.com/jacgrout/WebinarStats/blob/66de872bbfe665bc2193258bc00923b54ee31768/app.R#L95

**Comment by tomjemmett** [comment]
I suspect the issue here is that you are mixing a couple of things in one reactive, and it may be helpful to break into separate reactive/observers.

It's also to create the times using the `input$start_time`, when the intention is to set this input - I think that you want to be using some value from the data instead.

I would create separate reactives that would generate the start time and end time, then consume these in observers to update the time inputs, finally using these time reactives in the `get_joined` reactive

**Comment by craig-parylo** [comment]
I've had a go at writing a function to estimate start and end times (not a Shiny function though) and sent a pull request.

**Comment by jacgrout** [comment]
Thank you :-)
